= TODO
// for shortcuts like kbd:[Ctrl+a]
:experimental:

== Bugs

* [ ] interactive first start isn't animated when calling `global-...` because it starts the modes for each buffer and `interactive-p` fails for that (only animate current buffer and others only when switching windows?)
* [ ] when executing `M-x command` that shows a suggestion "You can run the command ...
with ...", recentering occurs after the message disappears (issue with `post-command-hook`?)
* [ ] with `ccm-vpos-up`/`ccm-vpos-down` set `vpos` is not remembered after buffer switch
* [ ] with `text-scale` not all lines are visible (middle line -- eg 10 of 20 -- is not centered)

== More

* [ ] recalculate cursor position on some events like after `(default-text-scale)` if necessary (hook for text properties?)
* [ ] (`while-no-input` ...), see `(describe-variable 'post-command-hook)`
* [ ] rename file to centered-cursor.el?
* [x] (80%?) reconsider customization for cursor position:
** no more `ccm-vpos-inverted` and more options: Center, Golden ratio, Golden ration from botton, Percentage, Lines from top or bottom
** simple symbol or integer or float for saving (and more robust with wrong customizations)
* [ ] when switching window, update vpos, maybe animation
* [ ] cursor position as window parameter instead of buffer local?
* [ ] use `vertical-motion`?
* [ ] `seq-do` instead of `mapcar` where possible
* [ ] when changing pos, save as new default (if customized → new defcustom)
* [ ] clicking scrollbar arrows should move cursor
* [ ] maybe: leave methods/context in sight

== Code hygiene

* [ ] replace tabs with spaces (`untabify`)
* [ ] use `package-lint` on source file

== Combatibility (with other packages etc.)

* [ ] package `default-text-scale`
* [ ] command `text-scale-increase` etc.
* [ ] package `undo-tree`
* [ ] consider `recenter-top-bottom`?
* [ ] https://emacs.stackexchange.com/questions/36094/using-ggtags-tag-lookup-along-with-centered-cursor-mode
* [ ] `evil-mode` (see https://github.com/andre-r/centered-cursor-mode.el/issues/11)
* [ ] `move-to-window-line-top-bottom`
* [ ] `text-scale`
* [ ] with line spacing
